{
  parserClass="com.intellij.perlplugin.language.PerlParser"
  parserUtilClass="com.intellij.perlplugin.language.PerlParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Perl"
  psiImplClassSuffix="Impl"
  psiPackage="com.intellij.perlplugin.psi"
  psiImplPackage="com.intellij.perlplugin.psi.impl"

  elementTypeHolderClass="com.intellij.perlplugin.psi.PerlTypes"
  elementTypeClass="com.intellij.perlplugin.psi.PerlElementType"
  tokenTypeClass="com.intellij.perlplugin.psi.PerlTokenType"
}

perlFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | (KEY? OPERATOR VALUE?)|  (KEY? '->' VALUE?)  | KEY {mixin="com.intellij.perlplugin.psi.impl.PerlNamedElementImpl"
                                                                                            implements="com.intellij.perlplugin.psi.PerlNamedElement" methods=[getKey getValue getName setName getNameIdentifier getPresentation]}